const fs = require('fs')

class Product {
    constructor({ id, title, description, price, thumbnail, code, stock, ...props }) {
        this.id = id
        this.title = title
        this.description = description
        this.price = price
        this.thumbnail = thumbnail
        this.code = code
        this.stock = stock
    }

    getData = () => {
        return ({
            id: this.id,
            title: this.title,
            description: this.description,
            price: this.price,
            thumbnail: this.thumbnail,
            code: this.code,
            stock: this.stock,
        })
    }
}

module.exports = class ProductManager {
    constructor(path) {
        this.id = 0
        this.path = path
        //fs.writeFileSync(path, JSON.stringify([]))
    }

    //Return all products
    getProducts = () => {
        let products = fs.readFileSync(this.path)
        return JSON.parse(products)
    }

    addProduct = ({ title, description, price, thumbnail, code, stock, ...props }) => {
        let products = this.getProducts()
        //Verify if code is duplicated and all fields exists
        if (products.some((x) => x.code === code) || !title || !description || !price || !thumbnail || !code || !stock) {

            //Duplicated code field
            !products.some((x) => x.code === code) || console.log(`Duplicated key ERROR: code ${code} is duplicated`)

            //Required fields
            title || console.log(`Validation ERROR: title is required`)
            description || console.log(`Validation ERROR: description is required`)
            price || console.log(`Validation ERROR: price is required`)
            thumbnail || console.log(`Validation ERROR: thumbnail is required`)
            code || console.log(`Validation ERROR: code is required`)
            stock || console.log(`Validation ERROR: stock is required`)

        } else {
            //New product instance
            const product = new Product({
                id: this.id, //use the autogenerated id 
                title: title,
                description: description,
                price: price,
                thumbnail: thumbnail,
                code: code,
                stock: stock
            })
            products.push(product.getData())



            //Save the file
            fs.writeFileSync(this.path, JSON.stringify(products))

            //Add 1 to the id
            ++this.id

            return products
        }
    }

    getProductById = (id) => {
        const products = this.getProducts()
        const product = products.filter((product) => product.id === id)

        //If the product exists return the product
        return product.toString() === "" ? "Not found" : product
    }

    deleteProduct = (id) => {
        const products = this.getProducts()
        const index = products.findIndex((product) => product.id === id)
        if (index > -1) {
            products.splice(index, 1);
            //Save the file
            fs.writeFileSync(this.path, JSON.stringify(products))
            return products
        } else {
            return ("Couldn't delete, product not found")
        }
    }

    updateProduct = ({ id, title, description, price, thumbnail, code, stock, ...props }) => {
        const products = this.getProducts()

        //Verify if code is duplicated and all fields exists
        if (products.some((x) => x.code === code) || !title || !description || !price || !thumbnail || !code || !stock) {

            //Duplicated code field
            !products.some((x) => x.code === code) || console.log(`Duplicated key ERROR: code ${code} is duplicated`)

            //Required fields
            id || console.log(`Validation ERROR: ID is required`)

        } else {

            const index = products.findIndex((product) => product.id === id)

            //New product instance
            products[index].title = title || products[index].title
            products[index].description = description || products[index].description
            products[index].price = price || products[index].price
            products[index].thumbnail = thumbnail || products[index].thumbnailW
            products[index].stock = stock || products[index].stock

            //Save the file
            fs.writeFileSync(this.path, JSON.stringify(products))
            return (products)
        }
    }
}
